### ISSUE TITLE
docker-compose failed

### ISSUE THREAD

**Issue by MaherJendoubi** [morita-it-lab/docker-centos-cscart#2]
λ docker-compose up
Creating network "mjendoubi_default" with the default driver
Pulling db (mariadb:latest)...
latest: Pulling from library/mariadb
5c90d4a2d1a8: Pull complete
89e2627e9201: Pull complete
76f6983b0fe0: Pull complete
653577605512: Pull complete
b72ef6e4e052: Pull complete
c6f30e5d6b91: Pull complete
e49ec6c374c5: Pull complete
814cc0bd9ff6: Pull complete
7e0ca5531f97: Pull complete
e63385a4e4cd: Pull complete
29959761c95f: Pull complete
8249d226685d: Pull complete
Digest: sha256:8f880226fb713d1ef3c320743a37dd2ed156cae07a6b0d0b8f32c247eaa06838
Status: Downloaded newer image for mariadb:latest
Creating cscart_mariadb
Creating cscart
Attaching to cscart_mariadb, cscart
cscart_mariadb | Initializing database
cscart    | Passing arguments to httpd using apachectl is no longer supported.
cscart    | You can only start/stop/restart httpd using this script.
cscart    | If you want to pass extra arguments to httpd, edit the
cscart    | /etc/sysconfig/httpd config file.
cscart_mariadb | 2016-07-25 15:21:00 139967606253504 [Note] /usr/sbin/mysqld (mysqld 10.1.16-MariaDB-1~jessie) starting as process 50 ...
cscart    | [Mon Jul 25 15:21:00.706049 2016] [suexec:notice] [pid 7] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
cscart    | [Mon Jul 25 15:21:00.785333 2016] [auth_digest:notice] [pid 7] AH01757: generating secret for digest authentication ...
cscart    | [Mon Jul 25 15:21:00.789539 2016] [lbmethod_heartbeat:notice] [pid 7] AH02282: No slotmem from mod_heartmonitor
cscart_mariadb | 2016-07-25 15:21:00 139967606253504 [Note] InnoDB: Using mutexes to ref count buffer pool pages
cscart_mariadb | 2016-07-25 15:21:00 139967606253504 [Note] InnoDB: The InnoDB memory heap is disabled
cscart_mariadb | 2016-07-25 15:21:00 139967606253504 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
cscart_mariadb | 2016-07-25 15:21:00 139967606253504 [Note] InnoDB: Memory barrier is not used
cscart_mariadb | 2016-07-25 15:21:00 139967606253504 [Note] InnoDB: Compressed tables use zlib 1.2.8
cscart_mariadb | 2016-07-25 15:21:00 139967606253504 [Note] InnoDB: Using Linux native AIO
cscart_mariadb | 2016-07-25 15:21:00 139967606253504 [Note] InnoDB: Using SSE crc32 instructions
cscart_mariadb | 2016-07-25 15:21:00 139967606253504 [Note] InnoDB: Initializing buffer pool, size = 256.0M
cscart_mariadb | 2016-07-25 15:21:00 139967606253504 [Note] InnoDB: Completed initialization of buffer pool
cscart    | [Mon Jul 25 15:21:00.876252 2016] [mpm_prefork:notice] [pid 7] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/5.6.23 configured -- resuming normal operations
cscart    | [Mon Jul 25 15:21:00.884937 2016] [core:notice] [pid 7] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
cscart_mariadb | 2016-07-25 15:21:00 139967606253504 [Warning] InnoDB: Failed to set O_DIRECT on file ./ibdata1: CREATE: Invalid argument, continuing anyway. O_DIRECT is known to result in 'Invalid argument' on Linux on tmpfs, see MySQL Bug#26662.
cscart_mariadb | 2016-07-25 15:21:00 139967606253504 [Note] InnoDB: The first specified data file ./ibdata1 did not exist: a new database to be created!
cscart_mariadb | 2016-07-25 15:21:00 139967606253504 [Note] InnoDB: Setting file ./ibdata1 size to 12 MB
cscart_mariadb | 2016-07-25 15:21:00 139967606253504 [Note] InnoDB: Database physically writes the file full: wait...
cscart_mariadb | 2016-07-25 15:21:00 139967606253504 [Note] InnoDB: Setting log file ./ib_logfile101 size to 48 MB
cscart_mariadb | 2016-07-25 15:21:01 139967606253504 [Note] InnoDB: Setting log file ./ib_logfile1 size to 48 MB
cscart_mariadb | 2016-07-25 15:21:01 139967606253504 [Note] InnoDB: Renaming log file ./ib_logfile101 to ./ib_logfile0
cscart_mariadb | 2016-07-25 15:21:01 139967606253504 [Warning] InnoDB: New log files created, LSN=45883
cscart_mariadb | 2016-07-25 15:21:01 139967606253504 [Note] InnoDB: Doublewrite buffer not found: creating new
cscart_mariadb | 2016-07-25 15:21:01 139967606253504 [Note] InnoDB: Doublewrite buffer created
cscart_mariadb | 2016-07-25 15:21:01 139967606253504 [Note] InnoDB: 128 rollback segment(s) are active.
cscart_mariadb | 2016-07-25 15:21:01 139967606253504 [Warning] InnoDB: Creating foreign key constraint system tables.
cscart_mariadb | 2016-07-25 15:21:01 139967606253504 [Note] InnoDB: Foreign key constraint system tables created
cscart_mariadb | 2016-07-25 15:21:01 139967606253504 [Note] InnoDB: Creating tablespace and datafile system tables.
cscart_mariadb | 2016-07-25 15:21:01 139967606253504 [Note] InnoDB: Tablespace and datafile system tables created.
cscart_mariadb | 2016-07-25 15:21:01 139967606253504 [Note] InnoDB: Waiting for purge to start
cscart_mariadb | 2016-07-25 15:21:01 139967606253504 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.30-76.3 started; log sequence number 0
cscart_mariadb | 2016-07-25 15:21:01 139966831101696 [Note] InnoDB: Dumping buffer pool(s) not yet started
cscart_mariadb | 2016-07-25 15:21:01 139967606253504 [ERROR] Can't init tc log
cscart_mariadb | 2016-07-25 15:21:01 139967606253504 [ERROR] Aborting
cscart_mariadb |
cscart_mariadb |
cscart_mariadb | Installation of system tables failed!  Examine the logs in
cscart_mariadb | /var/lib/mysql/ for more information.
cscart_mariadb |
cscart_mariadb | The problem could be conflicting information in an external
cscart_mariadb | my.cnf files. You can ignore these by doing:
cscart_mariadb |
cscart_mariadb |     shell> /usr/scripts/scripts/mysql_install_db --defaults-file=~/.my.cnf
cscart_mariadb |
cscart_mariadb | You can also try to start the mysqld daemon with:
cscart_mariadb |
cscart_mariadb |     shell> /usr/sbin/mysqld --skip-grant --general-log &
cscart_mariadb |
cscart_mariadb | and use the command line tool /usr/bin/mysql
cscart_mariadb | to connect to the mysql database and look at the grant tables:
cscart_mariadb |
cscart_mariadb |     shell> /usr/bin/mysql -u root mysql
cscart_mariadb |     mysql> show tables;
cscart_mariadb |
cscart_mariadb | Try 'mysqld --help' if you have problems with paths.  Using
cscart_mariadb | --general-log gives you a log in /var/lib/mysql/ that may be helpful.
cscart_mariadb |
cscart_mariadb | The latest information about mysql_install_db is available at
cscart_mariadb | https://mariadb.com/kb/en/installing-system-tables-mysql_install_db
cscart_mariadb | MariaDB is hosted on launchpad; You can find the latest source and
cscart_mariadb | email lists at http://launchpad.net/maria
cscart_mariadb |
cscart_mariadb | Please check all of the above before submitting a bug report
cscart_mariadb | at http://mariadb.org/jira
cscart_mariadb |
cscart_mariadb exited with code 1

**Comment by morita-it-lab** [comment]
Sorry... If Mac of Windows is Permission Error occurs.

Please remove the `- ./mariadb/database:/var/lib/mysql` from a **docker-compose.yml** .

**Comment by MaherJendoubi** [comment]
λ docker-compose up
Creating network "work_default" with the default driver
Pulling db (mariadb:latest)...
latest: Pulling from library/mariadb
5c90d4a2d1a8: Pull complete
89e2627e9201: Pull complete
76f6983b0fe0: Pull complete
653577605512: Pull complete
b72ef6e4e052: Pull complete
c6f30e5d6b91: Pull complete
e49ec6c374c5: Pull complete
814cc0bd9ff6: Pull complete
7e0ca5531f97: Pull complete
e63385a4e4cd: Pull complete
29959761c95f: Pull complete
8249d226685d: Pull complete
Digest: sha256:8f880226fb713d1ef3c320743a37dd2ed156cae07a6b0d0b8f32c247eaa06838
Status: Downloaded newer image for mariadb:latest
Creating my-cscart-mariadb
Creating my-cscart

ERROR: for cscart  Container command '/start.sh' not found or does not exist.
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose\cli\main.py", line 63, in main
AttributeError: 'ProjectError' object has no attribute 'msg'
docker-compose returned -1

**Comment by morita-it-lab** [comment]
`start.sh` is not exists...?

Do you have an edited file?

**Comment by MaherJendoubi** [comment]
Why Dockerfile and docker-compose.yml are not in the same folder?
What are the commands that you use please to run cscart on docker?

**Comment by MaherJendoubi** [comment]
BTW I'm running docker on windows 7

**Comment by morita-it-lab** [comment]
Thanks for making the #3. Write there.
